version: "3"
services:
  app:
    build: ./customers_api
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:8.0.29
    env_file: 
      - .env
    ports:
      - "32000:3306"
    volumes:
      - ./data/db:/var/lib/mysql