---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
  labels:
    app: customer-api
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: DB_NAME
              value: "customer_db"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"