---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: customer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: customer-api
          image: cusapi
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: DB_NAME
              value: "customer_db"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: customer-api-service
  labels:
    app: customer-api
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: customer-api
  type: LoadBalancer